name: test_services
services:

    test_server:
        container_name: test_server
        build:
          context: .
          dockerfile: TestApp.API/Data/Dockerfile
        ports:
          - "1433:1433"
        restart: unless-stopped

    testapp.api:
        container_name: test_api
        build:
          context: .
          dockerfile: TestApp.API/Dockerfile
        ports:
           - "5000:8080"
        depends_on:
          - test_server