name: Workflow Pipeline

on:
  push:
    branches:
      - develop

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip install safety
      - name: Scan for vulnerabilities
        run: safety scan



#  build-and-push:
#    needs: security
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3

#      - name: Build and push database
#        uses: docker/build-push-action@v6
#        with:
#          file: ./TestApp.API/Data/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/testapp-db:develop

#      - name: Build and push api
#        uses: docker/build-push-action@v6
#        with:
#          file: ./TestApp.API/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/testapp-api:develop





#      - name: Login to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

#      - name: Docker push image
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/testapp-db:develop


#      - name: Build docker image
#        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/testapp-api:develop -f TestApp.API/Dockerfile testapp-api/

#      - name: Docker push image
#        run: docker push ${{ secrets.DOCKER_USERNAME }}/testapp-api:develop